name: flutter_layout_grid_examples
description: Examples for flutter_layout_grid.
private: true

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_layout_grid:
    path: ../
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/periodic_table_data.json
