import 'package:flutter/material.dart';
import 'package:flutter_layout_grid/flutter_layout_grid.dart';

import 'big_grid_base.dart';

const nullCell = SizedBox(width: 0, height: 0);

bool needsPrint = true;

class BigGridNullCells extends BigGridBase {
  const BigGridNullCells({Key key, GlobalKey gridKey})
      : super(
          key: key,
          title: 'Empty cells are filled with an const, zero-sized SizedBox',
          gridKey: gridKey,
        );

  @override
  Widget buildGrid(GlobalKey gridKey) {
    return LayoutGrid(
      key: gridKey,
      columnSizes: repeat(14, [auto]),
      rowSizes: repeat(74, [auto]),
      children: [
        // 1
        Text('Item'),
        Text('Column 1'),
        Text('Column 2'),
        Text('Column 3'),
        Text('Col. 4'),
        Text('Col. 5'),
        Text('Col. 6').withGridPlacement(columnSpan: 2),
        Text('Col. 7'),
        Text('Col. 8'),
        Text('Col. 9'),
        Text('Col. 10'),
        Text('Col. 11'),
        Text('Col. 12'),
        // 2
        nullCell,
        Text('Commercial Designation'),
        Text('Grade'),
        Text('Maximum Span, m').withGridPlacement(rowSpan: 2),
        nullCell,
        nullCell,
        nullCell,
        nullCell,
        nullCell,
        nullCell,
        // 3
        nullCell,
        nullCell,
        nullCell,
        Text('Joists with Ceilings Attached to Wood Furring')
            .withGridPlacement(columnSpan: 7),
        Text('Joists with Concrete Topping').withGridPlacement(columnSpan: 3),
        // 4
        nullCell,
        nullCell,
        nullCell,
        nullCell,
        Text('Without Bridging').withGridPlacement(columnSpan: 3),
        Text('With Bridging').withGridPlacement(columnSpan: 4),
        Text('With or Without Bridging (2)').withGridPlacement(columnSpan: 3),
        // 5
        nullCell,
        nullCell,
        nullCell,
        nullCell,
        Text('Joist Spacing, mm').withGridPlacement(columnSpan: 3),
        Text('Joist Spacing, mm').withGridPlacement(columnSpan: 4),
        Text('Joist Spacing, mm').withGridPlacement(columnSpan: 3),
        // 6
        nullCell,
        nullCell,
        nullCell,
        nullCell,
        Text('305'),
        Text('406'),
        Text('610').withGridPlacement(columnSpan: 2),
        Text('305'),
        Text('406'),
        Text('610'),
        Text('305'),
        Text('406'),
        Text('610'),
        // 7
        Text('1.'),
        Text('Douglas Fir – Larch (includes Douglas Fir and Western Larch)')
            .withGridPlacement(rowSpan: 3),
        Text('Select'),
        Text('38 × 89'),
        Text('2.19'),
        Text('1.99'),
        Text('1.73').withGridPlacement(columnSpan: 2),
        Text('2.19'),
        Text('1.99'),
        Text('1.73'),
        Text('2.19'),
        Text('1.99'),
        Text('1.73'),
        // 8
        nullCell,
        Text('Structural'),
        Text('38 × 140'),
        Text('3.44'),
        Text('3.12'),
        Text('2.73').withGridPlacement(columnSpan: 2),
        Text('3.44'),
        Text('3.12'),
        Text('2.73'),
        Text('3.44'),
        Text('3.12'),
        Text('2.73'),
        // 9
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('4.24'),
        Text('3.99'),
        Text('3.59').withGridPlacement(columnSpan: 2),
        Text('4.52'),
        Text('4.11'),
        Text('3.59'),
        Text('4.52'),
        Text('4.11'),
        Text('3.59'),
        // 10
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.98'),
        Text('4.69'),
        Text('4.29').withGridPlacement(columnSpan: 2),
        Text('5.47'),
        Text('5.20'),
        Text('4.58'),
        Text('5.77'),
        Text('5.24'),
        Text('4.58'),
        // 11
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.67'),
        Text('5.34'),
        Text('4.88').withGridPlacement(columnSpan: 2),
        Text('6.19'),
        Text('5.89'),
        Text('5.54'),
        Text('6.83'),
        Text('6.37'),
        Text('5.58'),
        // 12
        nullCell,
        nullCell,
        Text('No. 1 and'),
        Text('38 × 89'),
        Text('2.09'),
        Text('1.90'),
        Text('1.66').withGridPlacement(columnSpan: 2),
        Text('2.09'),
        Text('1.90'),
        Text('1.66'),
        Text('2.09'),
        Text('1.90'),
        Text('1.66'),
        // 13
        nullCell,
        nullCell,
        Text('No. 2'),
        Text('38 × 140'),
        Text('3.29'),
        Text('2.99'),
        Text('2.62').withGridPlacement(columnSpan: 2),
        Text('3.29'),
        Text('2.99'),
        Text('2.62'),
        Text('3.29'),
        Text('2.99'),
        Text('2.55'),
        // 14
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('4.06'),
        Text('3.83'),
        Text('3.44').withGridPlacement(columnSpan: 2),
        Text('4.33'),
        Text('3.93'),
        Text('3.44'),
        Text('4.33'),
        Text('3.81'),
        Text('3.11'),
        // 15
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.78'),
        Text('4.50'),
        Text('4.11').withGridPlacement(columnSpan: 2),
        Text('5.24'),
        Text('4.98'),
        Text('4.31'),
        Text('5.37'),
        Text('4.65'),
        Text('3.80'),
        // 16
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.44'),
        Text('5.12'),
        Text('4.68').withGridPlacement(columnSpan: 2),
        Text('5.93'),
        Text('5.64'),
        Text('5.00'),
        Text('6.24'),
        Text('5.40'),
        Text('4.41'),
        // 17
        nullCell,
        nullCell,
        Text('No. 3'),
        Text('38 × 89'),
        Text('1.95'),
        Text('1.69'),
        Text('1.38').withGridPlacement(columnSpan: 2),
        Text('1.95'),
        Text('1.69'),
        Text('1.38'),
        Text('1.72'),
        Text('1.49'),
        Text('1.21'),
        // 18
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 140'),
        Text('2.78'),
        Text('2.41'),
        Text('1.97').withGridPlacement(columnSpan: 2),
        Text('2.78'),
        Text('2.41'),
        Text('1.97'),
        Text('2.45'),
        Text('2.12'),
        Text('1.73'),
        // 19
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('3.38'),
        Text('2.93'),
        Text('2.39').withGridPlacement(columnSpan: 2),
        Text('3.38'),
        Text('2.93'),
        Text('2.39'),
        Text('2.98'),
        Text('2.58'),
        Text('2.11'),
        // 20
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.14'),
        Text('3.58'),
        Text('2.93').withGridPlacement(columnSpan: 2),
        Text('4.14'),
        Text('3.58'),
        Text('2.93'),
        Text('3.65'),
        Text('3.16'),
        Text('2.58'),
        // 21
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('4.80'),
        Text('4.16'),
        Text('3.39').withGridPlacement(columnSpan: 2),
        Text('4.80'),
        Text('4.16'),
        Text('3.39'),
        Text('4.23'),
        Text('3.66'),
        Text('2.99'),
        // 22
        nullCell,
        nullCell,
        Text('Construction'),
        Text('38 × 89'),
        Text('2.03'),
        Text('1.84'),
        Text('1.61').withGridPlacement(columnSpan: 2),
        Text('2.03'),
        Text('1.84'),
        Text('1.61'),
        Text('2.03'),
        Text('1.84'),
        Text('1.61'),
        // 23
        nullCell,
        nullCell,
        Text('Standard'),
        Text('38 × 89'),
        Text('1.88'),
        Text('1.63'),
        Text('1.33').withGridPlacement(columnSpan: 2),
        Text('1.88'),
        Text('1.63'),
        Text('1.33'),
        Text('1.66'),
        Text('1.44'),
        Text('1.17'),
        // 24
        Text('2.'),
        Text('Hem – Fir (includes Western Hemlock and Amabilis Fir)')
            .withGridPlacement(rowSpan: 4),
        Text('Select'),
        Text('38 × 89'),
        Text('2.16'),
        Text('1.96'),
        Text('1.71').withGridPlacement(columnSpan: 2),
        Text('2.16'),
        Text('1.96'),
        Text('1.71'),
        Text('2.16'),
        Text('1.96'),
        Text('1.71'),
        // 25
        nullCell,
        Text('Structural'),
        Text('38 × 140'),
        Text('3.39'),
        Text('3.08'),
        Text('2.69').withGridPlacement(columnSpan: 2),
        Text('3.39'),
        Text('3.08'),
        Text('2.69'),
        Text('3.39'),
        Text('3.08'),
        Text('2.69'),
        // 26
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('4.18'),
        Text('3.94'),
        Text('3.54').withGridPlacement(columnSpan: 2),
        Text('4.46'),
        Text('4.05'),
        Text('3.54'),
        Text('4.46'),
        Text('4.05'),
        Text('3.54'),
        // 27
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.92'),
        Text('4.63'),
        Text('4.23').withGridPlacement(columnSpan: 2),
        Text('5.39'),
        Text('5.13'),
        Text('4.52'),
        Text('5.69'),
        Text('5.17'),
        Text('4.52'),
        // 28
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.60'),
        Text('5.27'),
        Text('4.82').withGridPlacement(columnSpan: 2),
        Text('6.10'),
        Text('5.81'),
        Text('5.47'),
        Text('6.74'),
        Text('6.28'),
        Text('5.50'),
        // 29
        nullCell,
        nullCell,
        Text('No. 1 and'),
        Text('38 × 89'),
        Text('2.09'),
        Text('1.90'),
        Text('1.66').withGridPlacement(columnSpan: 2),
        Text('2.09'),
        Text('1.90'),
        Text('1.66'),
        Text('2.09'),
        Text('1.90'),
        Text('1.66'),
        // 30
        nullCell,
        nullCell,
        Text('No. 2'),
        Text('38 × 140'),
        Text('3.29'),
        Text('2.99'),
        Text('2.62').withGridPlacement(columnSpan: 2),
        Text('3.29'),
        Text('2.99'),
        Text('2.62'),
        Text('3.29'),
        Text('2.99'),
        Text('2.62'),
        // 31
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('4.06'),
        Text('3.83'),
        Text('3.44').withGridPlacement(columnSpan: 2),
        Text('4.33'),
        Text('3.93'),
        Text('3.44'),
        Text('4.33'),
        Text('3.93'),
        Text('3.26'),
        // 32
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.78'),
        Text('4.50'),
        Text('4.11').withGridPlacement(columnSpan: 2),
        Text('5.24'),
        Text('4.98'),
        Text('4.39'),
        Text('5.53'),
        Text('4.88'),
        Text('3.99'),
        // 33
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.44'),
        Text('5.12'),
        Text('4.68').withGridPlacement(columnSpan: 2),
        Text('5.93'),
        Text('5.64'),
        Text('5.25'),
        Text('6.54'),
        Text('5.66'),
        Text('4.63'),
        // 34
        nullCell,
        nullCell,
        Text('No. 3.'),
        Text('38 × 89'),
        Text('2.03'),
        Text('1.84'),
        Text('1.61').withGridPlacement(columnSpan: 2),
        Text('2.03'),
        Text('1.84'),
        Text('1.61'),
        Text('2.03'),
        Text('1.83'),
        Text('1.50'),
        // 35
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 140'),
        Text('3.19'),
        Text('2.90'),
        Text('2.43').withGridPlacement(columnSpan: 2),
        Text('3.19'),
        Text('2.90'),
        Text('2.43'),
        Text('3.02'),
        Text('2.62'),
        Text('2.14'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('3.94'),
        Text('3.61'),
        Text('2.95').withGridPlacement(columnSpan: 2),
        Text('4.17'),
        Text('3.61'),
        Text('2.95'),
        Text('3.68'),
        Text('3.18'),
        Text('2.60'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.63'),
        Text('4.36'),
        Text('3.61').withGridPlacement(columnSpan: 2),
        Text('5.08'),
        Text('4.42'),
        Text('3.61'),
        Text('4.50'),
        Text('3.89'),
        Text('3.18'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.27'),
        Text('4.96'),
        Text('4.19').withGridPlacement(columnSpan: 2),
        Text('5.74'),
        Text('5.13'),
        Text('4.19'),
        Text('5.22'),
        Text('4.52'),
        Text('3.69'),
        //
        nullCell,
        nullCell,
        Text('Construction'),
        Text('38 × 89'),
        Text('2.03'),
        Text('1.84'),
        Text('1.61').withGridPlacement(columnSpan: 2),
        Text('2.03'),
        Text('1.84'),
        Text('1.61'),
        Text('2.03'),
        Text('1.84'),
        Text('1.61'),
        //
        nullCell,
        nullCell,
        Text('Standard'),
        Text('38 × 89'),
        Text('1.96'),
        Text('1.71'),
        Text('1.39').withGridPlacement(columnSpan: 2),
        Text('1.96'),
        Text('1.71'),
        Text('1.39'),
        Text('1.74'),
        Text('1.50'),
        Text('1.23'),
        //
        Text('3.'),
        Text('Spruce – Pine – Fir (includes Spruce (all species except Coast Sitka')
            .withGridPlacement(rowSpan: 6),

        Text('Select'),
        Text('38 × 89'),
        Text('2.06'),
        Text('1.87'),
        Text('1.64').withGridPlacement(columnSpan: 2),
        Text('2.06'),
        Text('1.87'),
        Text('1.64'),
        Text('2.06'),
        Text('1.87'),
        Text('1.64'),
        //
        nullCell,
        Text('Structural'),
        Text('38 × 140'),
        Text('3.24'),
        Text('2.95'),
        Text('2.57').withGridPlacement(columnSpan: 2),
        Text('3.24'),
        Text('2.95'),
        Text('2.57'),
        Text('3.24'),
        Text('2.95'),
        Text('2.57'),
        //
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('4.00'),
        Text('3.77'),
        Text('3.38').withGridPlacement(columnSpan: 2),
        Text('4.26'),
        Text('3.87'),
        Text('3.38'),
        Text('4.26'),
        Text('3.87'),
        Text('3.38'),
        //
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.70'),
        Text('4.43'),
        Text('4.05').withGridPlacement(columnSpan: 2),
        Text('5.16'),
        Text('4.91'),
        Text('4.32'),
        Text('5.45'),
        Text('4.95'),
        Text('4.32'),
        //
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.35'),
        Text('5.04'),
        Text('4.61').withGridPlacement(columnSpan: 2),
        Text('5.84'),
        Text('5.55'),
        Text('5.23'),
        Text('6.45'),
        Text('6.01'),
        Text('5.26'),
        //
        nullCell,
        Text('No. 1 and'),
        Text('38 × 89'),
        Text('1.99'),
        Text('1.81'),
        Text('1.58').withGridPlacement(columnSpan: 2),
        Text('1.99'),
        Text('1.81'),
        Text('1.58'),
        Text('1.99'),
        Text('1.81'),
        Text('1.58'),
        //
        nullCell,
        nullCell,
        Text('No. 2'),
        Text('38 × 140'),
        Text('3.14'),
        Text('2.85'),
        Text('2.49').withGridPlacement(columnSpan: 2),
        Text('3.14'),
        Text('2.85'),
        Text('2.49'),
        Text('3.14'),
        Text('2.85'),
        Text('2.49'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('3.87'),
        Text('3.64'),
        Text('3.27').withGridPlacement(columnSpan: 2),
        Text('4.12'),
        Text('3.75'),
        Text('3.27'),
        Text('4.12'),
        Text('3.75'),
        Text('3.27'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.55'),
        Text('4.28'),
        Text('3.91').withGridPlacement(columnSpan: 2),
        Text('4.99'),
        Text('4.75'),
        Text('4.18'),
        Text('5.27'),
        Text('4.79'),
        Text('4.13'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.18'),
        Text('4.88'),
        Text('4.46').withGridPlacement(columnSpan: 2),
        Text('5.65'),
        Text('5.37'),
        Text('5.06'),
        Text('6.23'),
        Text('5.81'),
        Text('4.79'),
        //
        nullCell,
        nullCell,
        Text('No. 3'),
        Text('38 × 89'),
        Text('1.96'),
        Text('1.78'),
        Text('1.55').withGridPlacement(columnSpan: 2),
        Text('1.96'),
        Text('1.78'),
        Text('1.55'),
        Text('1.96'),
        Text('1.78'),
        Text('1.50'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 140'),
        Text('3.08'),
        Text('2.80'),
        Text('2.43').withGridPlacement(columnSpan: 2),
        Text('3.08'),
        Text('2.80'),
        Text('2.43'),
        Text('3.02'),
        Text('2.62'),
        Text('2.14'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('3.80'),
        Text('3.58'),
        Text('2.95').withGridPlacement(columnSpan: 2),
        Text('4.05'),
        Text('3.61'),
        Text('2.95'),
        Text('3.68'),
        Text('3.18'),
        Text('2.60'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.47'),
        Text('4.21'),
        Text('3.61').withGridPlacement(columnSpan: 2),
        Text('4.90'),
        Text('4.42'),
        Text('3.61'),
        Text('4.50'),
        Text('3.89'),
        Text('3.18'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('5.09'),
        Text('4.79'),
        Text('4.19').withGridPlacement(columnSpan: 2),
        Text('5.55'),
        Text('5.13'),
        Text('4.19'),
        Text('5.22'),
        Text('4.52'),
        Text('3.69'),
        //
        nullCell,
        nullCell,
        Text('Construction'),
        Text('38 × 89'),
        Text('1.96'),
        Text('1.78'),
        Text('1.55').withGridPlacement(columnSpan: 2),
        Text('1.96'),
        Text('1.78'),
        Text('1.55'),
        Text('1.96'),
        Text('1.78'),
        Text('1.55'),
        //
        nullCell,
        nullCell,
        Text('Standard'),
        Text('38 × 89'),
        Text('1.88'),
        Text('1.71'),
        Text('1.44').withGridPlacement(columnSpan: 2),
        Text('1.88'),
        Text('1.71'),
        Text('1.44'),
        Text('1.80'),
        Text('1.56'),
        Text('1.27'),
        //
        Text('4.'),
        Text('Northern Species (includes any Canadian Species covered by the NLGA')
            .withGridPlacement(rowSpan: 5),

        Text('Select'),
        Text('38 × 89'),
        Text('1.84'),
        Text('1.68'),
        Text('1.46').withGridPlacement(columnSpan: 2),
        Text('1.84'),
        Text('1.68'),
        Text('1.46'),
        Text('1.84'),
        Text('1.68'),
        Text('1.46'),
        //
        nullCell,
        Text('Structural'),
        Text('38 × 140'),
        Text('2.90'),
        Text('2.63'),
        Text('2.30').withGridPlacement(columnSpan: 2),
        Text('2.90'),
        Text('2.63'),
        Text('2.30'),
        Text('2.90'),
        Text('2.63'),
        Text('2.30'),
        //
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('3.58'),
        Text('3.37'),
        Text('3.03').withGridPlacement(columnSpan: 2),
        Text('3.81'),
        Text('3.46'),
        Text('3.03'),
        Text('3.81'),
        Text('3.46'),
        Text('3.03'),
        //
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.20'),
        Text('3.96'),
        Text('3.62').withGridPlacement(columnSpan: 2),
        Text('4.61'),
        Text('4.39'),
        Text('3.86'),
        Text('4.87'),
        Text('4.42'),
        Text('3.86'),
        //
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('4.79'),
        Text('4.51'),
        Text('4.12').withGridPlacement(columnSpan: 2),
        Text('5.22'),
        Text('4.96'),
        Text('4.68'),
        Text('5.76'),
        Text('5.37'),
        Text('4.54'),
        //
        nullCell,
        nullCell,
        Text('No. 1 and'),
        Text('38 × 89'),
        Text('1.80'),
        Text('1.64'),
        Text('1.43').withGridPlacement(columnSpan: 2),
        Text('1.80'),
        Text('1.64'),
        Text('1.43'),
        Text('1.80'),
        Text('1.64'),
        Text('1.43'),
        //
        nullCell,
        nullCell,
        Text('No. 2'),
        Text('38 × 140'),
        Text('2.83'),
        Text('2.57'),
        Text('2.25').withGridPlacement(columnSpan: 2),
        Text('2.83'),
        Text('2.57'),
        Text('2.25'),
        Text('2.83'),
        Text('2.57'),
        Text('2.23'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('3.50'),
        Text('3.29'),
        Text('2.96').withGridPlacement(columnSpan: 2),
        Text('3.72'),
        Text('3.38'),
        Text('2.96'),
        Text('3.72'),
        Text('3.32'),
        Text('2.71'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.11'),
        Text('3.87'),
        Text('3.54').withGridPlacement(columnSpan: 2),
        Text('4.51'),
        Text('4.29'),
        Text('3.76'),
        Text('4.69'),
        Text('4.06'),
        Text('3.31'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('4.68'),
        Text('4.40'),
        Text('4.03').withGridPlacement(columnSpan: 2),
        Text('5.10'),
        Text('4.85'),
        Text('4.36'),
        Text('5.44'),
        Text('4.71'),
        Text('3.84'),
        //
        nullCell,
        nullCell,
        Text('No. 3'),
        Text('38 × 89'),
        Text('1.76'),
        Text('1.60'),
        Text('1.36').withGridPlacement(columnSpan: 2),
        Text('1.76'),
        Text('1.60'),
        Text('1.36'),
        Text('1.70'),
        Text('1.47'),
        Text('1.20'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 140'),
        Text('2.75'),
        Text('2.38'),
        Text('1.94').withGridPlacement(columnSpan: 2),
        Text('2.75'),
        Text('2.38'),
        Text('1.94'),
        Text('2.42'),
        Text('2.10'),
        Text('1.71'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 184'),
        Text('3.35'),
        Text('2.90'),
        Text('2.37').withGridPlacement(columnSpan: 2),
        Text('3.35'),
        Text('2.90'),
        Text('2.37'),
        Text('2.95'),
        Text('2.55'),
        Text('2.08'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 235'),
        Text('4.01'),
        Text('3.54'),
        Text('2.89').withGridPlacement(columnSpan: 2),
        Text('4.09'),
        Text('3.54'),
        Text('2.89'),
        Text('3.61'),
        Text('3.12'),
        Text('2.55'),
        //
        nullCell,
        nullCell,
        nullCell,
        Text('38 × 286'),
        Text('4.56'),
        Text('4.11'),
        Text('3.36').withGridPlacement(columnSpan: 2),
        Text('4.75'),
        Text('4.11'),
        Text('3.36'),
        Text('4.18'),
        Text('3.62'),
        Text('2.96'),
        //
        nullCell,
        nullCell,
        Text('Construction'),
        Text('38 × 89'),
        Text('1.76'),
        Text('1.60'),
        Text('1.40').withGridPlacement(columnSpan: 2),
        Text('1.76'),
        Text('1.60'),
        Text('1.40'),
        Text('1.76'),
        Text('1.60'),
        Text('1.37'),
        //
        nullCell,
        nullCell,
        Text('Standard'),
        Text('38 × 89'),
        Text('1.63'),
        Text('1.41'),
        Text('1.15').withGridPlacement(columnSpan: 2),
        Text('1.63'),
        Text('1.41'),
        Text('1.15'),
        Text('1.44'),
        Text('1.25'),
        Text('1.02'),
      ],
    );
  }
}
