name: test
on:
  push:
  pull_request:
    branches:
    - main
  schedule:
  # Run the quality job at 4am every day
  - cron: '0 4 * * *'

jobs:
  test:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'beta'

    # Get flutter dependencies.
    - run: flutter pub get

    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .

    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .

    # Do the same for examples
    - run: flutter analyze .
      working-directory: ./example

    # Run widget tests for our flutter project.
    - run: flutter test
